version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.1
    container_name: zookeeper
    restart: unless-stopped
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:7.3.1
    container_name: kafka
    hostname: kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9094,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://:9094,OUTSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD-SHELL", "nc -zv localhost 9092"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - kafka-network

  kafka-rest-proxy:
    image: confluentinc/cp-kafka-rest:7.3.1
    container_name: kafka-rest-proxy
    hostname: kafka-rest-proxy
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082/
      KAFKA_REST_HOST_NAME: kafka-rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9094
    depends_on:
      - zookeeper
      - kafka
    networks:
      - kafka-network

  kafka-topics-ui:
    image: landoop/kafka-topics-ui:0.9.4
    container_name: kafka-topics-ui
    hostname: kafka-topics-ui
    ports:
      - "9000:8000"
    environment:
      KAFKA_REST_PROXY_URL: "http://kafka-rest-proxy:8082/"
      PROXY: "true"
    depends_on:
      - zookeeper
      - kafka
      - kafka-rest-proxy
    networks:
      - kafka-network

  mongo:
    hostname: mongo
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    networks:
      - kafka-network
    command: mongod --replSet my-mongo-set
    healthcheck:
      test: echo 'db.stats().ok' | mongosh localhost:27017/schools --quiet

  mongoinit:
    image: mongo
    # this container will exit after executing the command
    restart: "no"
    depends_on:
      - mongo
    command: >
      mongosh --host mongo:27017 --eval
      'config = {"_id" : "my-mongo-set","members" : [{"_id":0, "host":"mongo:27017"}]};
      rs.initiate(config);'
    networks:
      - kafka-network

  connect:
    image: quay.io/debezium/connect:2.0
    ports:
      - 8083:8083
    links:
      - kafka
      - mongo
    environment:
      GROUP_ID: 1
      BOOTSTRAP_SERVERS: kafka:9094
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
    networks:
      - kafka-network

networks:
  kafka-network:
#    name: "kafka_default"